### ISSUE TITLE
ta tudo uma merda

### ISSUE THREAD

**Issue by joaobenedetmachado** [Pedro-Luucas/servico-social#1]
**pedrao faca o favor de excluir este repositorio**

**Comment by Pedro-Luucas** [comment]
A sociedade industrial e suas consequências têm sido um desastre para a raça humana. Elas não apenas aumentaram em muito a expectativa de vida nos países "avançados", como também desestabilizaram a sociedade, tornaram a vida frustrante, sujeitaram os seres humanos a indignidades, provocaram sofrimento psicológico generalizado (no Terceiro Mundo, sofrimentos físicos também) e infligiram graves danos ao mundo natural. O contínuo desenvolvimento da tecnologia irá agravar essa situação.
O sistema tecnológico industrial poderá sobreviver, ou poderá entrar em colapso. Se sobreviver, é possível -apenas possível- que com o tempo chegue a um nível reduzido de sofrimento físico e psicológico. Mas isso só poderá acontecer depois de passado um período longo e muito doloroso de adaptação, e apenas ao custo da redução permanente dos seres humanos e muitos outros organismos vivos à situação de produtos criados artificialmente e meras peças na máquina social.
Se o sistema entrar em colapso, as consequências serão muito dolorosas. Mas quanto mais o sistema crescer mais desastrosos serão os resultados de sua ruptura. Portanto, se pretendemos provocar sua ruptura é melhor fazê-lo mais cedo do que mais tarde.
Por essas razões defendemos uma revolução contra o sistema industrial. Essa revolução pode ou não fazer uso da violência. Ela poderá ser repentina ou ser um processo relativamente gradativo, estendendo-se por algumas décadas.
A Psicologia do Esquerdismo Moderno
Uma das manifestações mais difundidas da doidice de nosso mundo é o esquerdismo, de modo que uma discussão da psicologia do esquerdismo pode funcionar como introdução à discussão da sociedade moderna.
Chamamos às duas tendências psicológicas subjacentes ao esquerdismo moderno de "sentimentos de inferioridade" e "supersocialização".
Quando dizemos "sentimentos de inferioridade" queremos dizer não apenas sentimentos de inferioridade no sentido restrito do termo, mas todo um espectro de traços relacionados: baixa auto-estima, sentimentos de impotência, tendências depressivas, derrotismo, culpa, raiva de si mesmo, etc...
Os esquerdistas são hipersensíveis em relação às palavras usadas para designar integrantes de minorias e a qualquer coisa que seja dita relativa às minorias. Os termos "negro", "oriental", "deficiente físico" ou "gata" para designar um africano, um asiático, uma pessoa incapacitada ou uma mulher não tinham, originalmente, qualquer conotação pejorativa.
Muitos esquerdistas identificam-se profundamente com os problemas de grupos que transmitem imagens de fracos (mulheres), derrotados (índios americanos), repulsivos (homossexuais) ou inferiores de alguma outra maneira. Os próprios esquerdistas sentem que esses grupos são inferiores. Jamais admitiriam a si mesmos que têm tais sentimentos, mas é porque realmente vêem esses grupos como inferiores que se identificam com seus problemas.
Os esquerdistas tendem a odiar qualquer coisa que transmita a imagem de ser forte, bom e bem-sucedido. Eles odeiam os EUA, odeiam a civilização ocidental, odeiam os homens brancos, odeiam o que é racional.
Note-se a tendência masoquista das táticas esquerdistas. Os esquerdistas fazem protestos deitando-se no chão na frente de veículos. Nesses protestos, eles provocam a polícia, intencionalmente, a cometer abusos contra eles. Essas táticas podem muitas vezes funcionar, mas muitos esquerdistas as utilizam não como meios para atingir um fim, mas porque preferem táticas masoquistas. O ódio a si mesmo é uma característica esquerdista.
Se nossa sociedade não tivesse nenhum problema, os esquerdistas teriam que inventar problemas para conseguir armar confusão.
Supersocialização
Algumas pessoas são tão altamente socializadas que a tentativa de pensar, sentir e agir moralmente impõe um peso muito grande a elas. Para evitar seus sentimentos de culpa, elas precisam enganar-se continuamente sobre suas verdadeiras motivações e encontrar explicações morais para sentimentos e atos que na realidade têm uma origem não moral. Utilizamos o termo "supersocializado" para descrever tais pessoas.
Sugerimos que a supersocialização é uma das piores crueldades que os seres humanos infligem uns aos outros.
O processo do poder
Os seres humanos têm a necessidade (provavelmente originária de razões biológicas) de algo ao qual chamaremos "processo do poder". Este processo está intimamente ligado à necessidade de poder (que é amplamente reconhecida), mas não é exatamente a mesma coisa.
É verdade que alguns indivíduos parecem ter pouca necessidade de autonomia. Ou seu desejo de poder é fraco, ou elas o satisfazem através da identificação com alguma organização poderosa da qual fazem parte. E existem também aquelas pessoas que não pensam, tipos animais que parecem se satisfazer com uma sensação de poder puramente físico.
Mas para a maioria das pessoas, é por meio do processo do poder que se adquire auto-estima, autoconfiança e um senso de poder -ter uma meta, fazer um esforço autônomo e atingir essa meta. Quando não se tem uma oportunidade adequada de viver o processo de poder, as consequências são (dependendo do indivíduo e da maneira pela qual o processo de poder é perturbado) tédio, desmoralização, baixa auto-estima, sentimentos de inferioridade, derrotismo, depressão, ansiedade, sentimentos de culpa, frustração, hostilidade, abuso de cônjuge ou crianças, hedonismo insaciável, comportamentos sexuais anormais, desordens do sono, desordens alimentares, etc.
Raízes dos Problemas Sociais
Atribuímos os problemas sociais e psicológicos da sociedade moderna ao fato de que a sociedade exige que as pessoas vivam sob condições radicalmente diferentes daquelas nas quais a raça humana evoluiu, e se comportem de maneiras que entram em conflito com os padrões de comportamento que a raça humana desenvolveu enquanto vivia sob condições anteriores.
Entre as condições anormais presentes na sociedade industrial moderna figuram a densidade demográfica excessiva, a separação entre o homem e a natureza, a rapidez excessiva das transformações sociais e a ruptura das comunidades naturais em pequena escala, como a família extensa, a aldeia ou a tribo.
Os conservadores são idiotas: eles se queixam da decadência dos valores tradicionais, mas apóiam entusiasticamente o progresso tecnológico e o crescimento econômico. Ao que parece, nunca lhes ocorre que não se pode operar transformações drásticas e velozes na tecnologia e economia de uma sociedade sem provocar transformações velozes em todos os outros aspectos da sociedade também, e que tais transformações velozes levam inevitavelmente à ruptura dos valores tradicionais.
Outra razão pela qual a sociedade não pode ser reformada em favor da liberdade é que a tecnologia moderna é um sistema unificado no qual todas as partes são interdependentes. Não se pode livrar-se das partes "ruins" da tecnologia e manter apenas as partes "boas". Tomemos o caso da medicina moderna. Os avanços na ciência médica dependem dos avanços nos campos da química, física, biologia, informática e outros. Os tratamentos médicos avançados exigem equipamentos caros de alta tecnologia que só podem ser assegurados por uma sociedade tecnologicamente progressiva e economicamente rica. É evidente que não se pode ter muitos progressos na medicina sem o sistema tecnológico inteiro e tudo que o acompanha.
Revolução é mais fácil do que reforma
A única saída é dispensar o sistema tecnológico industrial inteiro. Isso implica uma revolução, não necessariamente um levante armado, mas com certeza uma transformação radical e fundamental da natureza da sociedade.
O que sugerimos é que a raça humana poderia facilmente chegar a um ponto em que sua dependência das máquinas seria tão grande que não lhe restaria nenhuma opção prática senão aceitar todas as decisões das máquinas. À medida que a sociedade e os problemas que a confrontam se tornam mais e mais complexos e as máquinas ficam mais e mais inteligentes, as pessoas vão deixar as máquinas tomarem cada vez mais decisões em seu lugar, simplesmente porque as decisões tomadas pelas máquinas trarão melhores resultados do que as decisões tomadas pelos homens. Com o tempo, é possível que se chegue a um estágio em que as decisões necessárias para manter o sistema funcionando sejam tão complexas que os seres humanos serão incapazes de tomá-las inteligentemente. Quando se chegar a esse estágio, as máquinas estarão, efetivamente, no controle. As pessoas não poderão simplesmente desligar as máquinas porque elas estarão tão dependentes delas que desligá-las equivaleria a cometer suicídio.
Estratégia
As duas principais tarefas para o presente são promover o estresse social e a instabilidade na sociedade industrial, e desenvolver e difundir uma ideologia que se oponha à tecnologia e ao sistema industrial. Quando o sistema ficar suficientemente estressado e instável, uma revolução contra a tecnologia pode tornar-se possível.
Quanto às consequências negativas da eliminação da sociedade industrial, bem, dois proveitos não cabem num saco só. Para ganhar uma coisa, é preciso sacrificar outra.
A maioria das pessoas odeia conflitos psicológicos. Por essa razão elas evitam pensar seriamente sobre qualquer problema social grave, e gostam que esses problemas lhes sejam apresentados em termos simples, preto no branco. A revolução precisa ser internacional e mundial. Ela não pode ser realizada de nação em nação. Toda vez que se sugere que os EUA, por exemplo, deveriam frear seu progresso tecnológico ou crescimento econômico, as pessoas ficam histéricas e começam a gritar que se cairmos para segundo lugar em termos tecnológicos os japoneses vão assumir a dianteira.
Seria inútil os revolucionários tentarem atacar o sistema sem utilizar um pouco da tecnologia moderna. Eles precisam, no mínimo, utilizar a mídia para divulgar sua mensagem. Mas deveriam recorrer à tecnologia moderna para apenas um fim: atacar o sistema tecnológico.
Com relação à estratégia revolucionária, os únicos pontos sobre os quais insistimos totalmente são que a única meta que se sobrepõe a todas as outras deve ser a eliminação da tecnologia moderna, e que não se deve permitir que nenhuma outra meta compita com essa.
